# Generated by Django 4.2.5 on 2023-10-14 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Walk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_time", models.DateTimeField()),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("status", models.CharField(default="Scheduled", max_length=20)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks_as_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "walker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks_as_walker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalkLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("walk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="walks.walk")),
            ],
        ),
        migrations.CreateModel(
            name="WalkHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_time", models.DateTimeField()),
                ("distance", models.DecimalField(decimal_places=2, max_digits=6)),
                ("walker_rating", models.PositiveIntegerField(default=0)),
                ("owner_rating", models.PositiveIntegerField(default=0)),
                ("walk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="walks.walk")),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("claim_status", models.CharField(default="Pending", max_length=20)),
                (
                    "claimant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("walk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="walks.walk")),
            ],
        ),
    ]
